# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Clogii' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Clogii
  
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

  target 'ClogiiTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Clogii-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Clogii-tvOS

  target 'Clogii-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
